export const darkMapStyle = [
  { elementType: 'geometry', stylers: [{ color: '#242438' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#b0b0b0' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#242438' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#2d2d44' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#c0c0c0' }] },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#2d2d44' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#888888' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#3d3d5c' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#2a2a44' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#9e9e9e' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#4a4a6e' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#50507a' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#2e2e4c' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#f0c880' }] },
  { featureType: 'road.local', elementType: 'geometry', stylers: [{ color: '#3a3a58' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#1a2a4a' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#6a7a8a' }] },
  { featureType: 'landscape.natural', elementType: 'geometry', stylers: [{ color: '#2a2a40' }] },
];

export const lightMapStyle = [
  { elementType: 'geometry', stylers: [{ color: '#f8f8f8' }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#616161' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#f5f5f5' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#ffffff' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#eeeeee' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#9e9e9e' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#ffffff' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#ededed' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#dcdcdc' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#757575' }] },
  { featureType: 'road.local', elementType: 'labels.text.fill', stylers: [{ color: '#9e9e9e' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#b3d1f0' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#9e9e9e' }] },
  { featureType: 'landscape.natural', elementType: 'geometry', stylers: [{ color: '#f0f4e8' }] },
];
